# Generated by Django 5.0.3 on 2024-03-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imageurl_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageURL',
        ),
    ]
