# Generated by Django 3.2.12 on 2024-03-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
