# Generated by Django 5.0.3 on 2024-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_path',
            field=models.TextField(default=1, verbose_name='http://127.0.0.1:8000'),
            preserve_default=False,
        ),
    ]
