# Generated by Django 5.0.3 on 2024-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_image_full_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='full_path',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=255),
        ),
    ]
